1-03-2019_1.00am/bloodBank2/api/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken.views import obtain_auth_token
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name="index"),
    path('post/', views.Register.as_view()),
    path('profile/', views.Profile.as_view()),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('groups/', views.Groups.as_view()),
    path('friend/', views.Friend.as_view()),
    path('userUpdate/<int:pk>/', views.UserUpdateView.as_view()),
    path('friendRequests/', views.FriendRequest.as_view()),
    path('feed/', views.FeedView.as_view()),
    path('getProfileView/', views.ProfileView.as_view()),
    path('profilePost/', views.PostProfile.as_view()),
    path('friendList/', views.FriendListView.as_view()),
    path('getGroupPost/<int:pk>/', views.GetGroupPosts.as_view()),
    path('likePost/', views.LikePost.as_view()),
    path('joinGroup/', views.JoinGroup.as_view()),
    path('admin-post/', views.AddGroupPost.as_view()),
    path('group-add/', views.CreateGroup.as_view()),
    path('forgot-password/', views.forgotPassword),
    url(r'^group-update/(?P<pk>\d+)/$', views.GroupUpdateView.as_view()),
    url(r'^group-accept/(?P<userid>\d+)/(?P<groupid>\d+)/$', views.acceptGroupRequest),
    url(r'^group-reject/(?P<userid>\d+)/(?P<groupid>\d+)/$', views.removeUser),
    path('admin-login/', views.logged),
    path('admin-panel/',views.adminPanel),
    path('create-form-post/',views.createFormPost.as_view()),
    path('getFormPost/<int:pk>/', views.GetFormPosts.as_view()),
    path('send-response/', views.getFormResponse.as_view()),
    path('logout/',views.logoutAdmin),
    path('friendPosts/<int:pk>/',views.getFriendPosts.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

1-03-2019_1.00am/bloodBank2/bloodBank2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls'))
]

1-03-2019_1.00am/bloodBank2/api/models.py
import uuid
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser, Group


# Create your models here.

class CustomUser(AbstractUser):
    dob = models.DateField(null=True)
    bloodGroup = models.CharField(max_length=3)
    gender = models.BooleanField(default=True)
    address = models.CharField(max_length=80)
    phone = models.IntegerField(default=0, unique=True)
    username = models.CharField(max_length=20, unique=False, default="")
    profilePic = models.ImageField(upload_to="media/", blank=True, null=True)
    friends = models.ManyToManyField("self", blank=True)
    friendRequests = models.ManyToManyField("self", blank=True, symmetrical=False)
    education = models.CharField(max_length=30, unique=False, default="", editable=True,null=True)
    adhaarNo = models.CharField(max_length=16, unique=False, default="", editable=True,null=True)
    profession = models.CharField(max_length=30, unique=False, default="", editable=True,null=True)
    emergencyContact = models.IntegerField(default=0, editable=True)
    officeAddress = models.CharField(max_length=100, default="", editable=True,null=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['username', 'email']

    def __str__(self):
        return self.first_name + " " + self.last_name + " - " + str(self.phone)


class Group(models.Model):
    title = models.CharField(max_length=20)
    description = models.CharField(max_length=150)
    user = models.ManyToManyField(CustomUser, blank=True)
    image = models.ImageField(upload_to="media/", blank=True, null=True)
    pendingGroupRequest = models.ManyToManyField(CustomUser, related_name="user_content_type", blank=True)

    def __str__(self):
        return self.title


class GroupPost(models.Model):
    postDetails = models.CharField(max_length=300)
    time = models.DateTimeField(auto_now_add=True)
    group = models.ManyToManyField(Group)
    image = models.ImageField(upload_to="media/", blank=True, null=True)

    def __str__(self):
        self.string = ""
        for i in self.group.all():
            self.string = self.string + i.title + ","
        return self.string + " - " + self.postDetails


class ProfilePost(models.Model):
    postDetails = models.CharField(max_length=300)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="media/", blank=True, null=True)
    likes = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user) + " - " + self.postDetails


class FormPost(models.Model):
    postDetails = models.CharField(max_length=200, null=True)
    group = models.ManyToManyField(Group, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.postDetails)


class FormData(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    time = models.CharField(max_length=300)
    post = models.ForeignKey(FormPost, blank=True, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.user)

1-03-2019_1.00am/bloodBank2/api/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.generics import UpdateAPIView
from .serializers import *
from rest_framework import generics, status
from rest_framework.response import Response
from twilio.rest import Client
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import MultiPartParser
from collections import namedtuple
from django.contrib.auth import authenticate, login, logout
from django.core.mail import EmailMessage


# Create your views here.
def index(request):
    return render(request, 'login.html')


def sendSmsAndEmail(request):
    users = CustomUser.objects.all()
    for user in users:
        email = EmailMessage('Jankalyan blood bank alert', 'Email from jankalyan blood bank', to=[user.email])
        email.send()
        account_sid = 'AC83dde2f67b767323e2ad9f11cae52a67'
        auth_token = '3501bf6737be8a4c91a082768320eeac'
        client = Client(account_sid, auth_token)
        sms = client.messages.create(
            from_="+12056490939",
            body="this is message sent to you by omkar from django",
            to="+91" + str(user.phone)
        )
        print(sms.sid)
    return HttpResponse("message google sent")


class UserUpdateView(UpdateAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserSerializer

    def get_queryset(self):
        return CustomUser.objects.all()


class Register(APIView):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

    parser_classes = (MultiPartParser,)

    def post(self, request, *args, **kwargs):
        serializer = UserSerializer(data=request.data)
        print(request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Profile(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserSerializer

    def get_queryset(self):
        return CustomUser.objects.filter(phone=self.request.user.phone)


class Groups(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        GroupTuple = namedtuple("Groups", ('yourGroups', 'otherGroups'))

        yourGroups = request.user.group_set.all()
        otherGroups = Group.objects.exclude(user=request.user)

        group = GroupTuple(yourGroups=yourGroups, otherGroups=otherGroups)
        serializer = GroupViewSerializer(group)
        return Response(serializer.data, status=status.HTTP_200_OK)


class Friend(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserSerializer

    def post(self, request, *args, **kwargs):
        phone = request.data["phone"]
        u = CustomUser.objects.get(phone=phone)
        u.friendRequests.add(request.user)
        return Response(status=status.HTTP_200_OK)

    def get_queryset(self):
        return self.request.user.friends.all()


class FriendRequest(generics.ListAPIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = UserSerializer

    def post(self, request, *args, **kwargs):
        phone = request.data["phone"]
        u = CustomUser.objects.get(phone=phone)

        if request.user.friendRequests.filter(phone=u.phone).exists():
            request.user.friendRequests.remove(u)
            request.user.friends.add(u)
            return Response(status=status.HTTP_200_OK)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    def get_queryset(self):
        return self.request.user.friendRequests.all()


class FeedView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        Feed = namedtuple("Feed", ('groupPosts', 'profilePosts', 'formPosts'))
        groups = request.user.group_set.all()
        friends = request.user.friends.all()
        groupPostList = set()
        profilePostList = []
        formPostList = set()

        for g in groups:
            for i in g.grouppost_set.all().order_by('-id')[:3]:
                groupPostList.add(i)

            for j in g.formpost_set.all().order_by('-id')[:3]:
                formPostList.add(j)
        profilePostList += request.user.profilepost_set.all().order_by('-id')[:2]
        for f in friends:
            profilePostList += f.profilepost_set.all().order_by('-id')[:4]

        # groupPostList = list(groupPostList)
        # formPostList = list(formPostList)
        # profilePostList.reverse()
        # groupPostList.reverse()
        # formPostList.reverse()
        feed = Feed(groupPosts=groupPostList, profilePosts=profilePostList, formPosts=formPostList)
        serializer = FeedSerializer(feed)
        return Response(serializer.data, status=status.HTTP_200_OK)


class GetGroupPosts(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request, pk):
        Posts = namedtuple("Feed", ('groupPosts', 'formPosts'))
        g = Group.objects.get(pk=pk)
        gp = g.grouppost_set.all().order_by("-id")
        fp = g.formpost_set.all().order_by("-id")

        groupPosts = Posts(groupPosts=gp, formPosts=fp)
        serializer = GroupPageSerializer(groupPosts)
        return Response(serializer.data, status=status.HTTP_200_OK)


class ProfileView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        ProfileTuple = namedtuple("Profile", ('suggestions', 'profilePosts'))

        posts = request.user.profilepost_set.all().order_by('-id')

        friends = request.user.friends.all() | CustomUser.objects.filter(
            phone=request.user.phone) | request.user.friendRequests.all()
        s = CustomUser.objects.difference(friends)
        profile = ProfileTuple(suggestions=s[:5], profilePosts=posts)
        serializer = ProfileSerializer(profile)
        return Response(serializer.data, status=status.HTTP_200_OK)


class PostProfile(APIView):
    permission_classes = (IsAuthenticated,)
    serializer_class = ProfilePostSerializer

    parser_classes = (MultiPartParser,)

    def post(self, request, *args, **kwargs):
        p = ProfilePost.objects.create(user=request.user, postDetails=request.data["postDetails"])
        try:
            p.image = request.data["image"]
        except():
            p.image = None
        p.save()
        return Response(status=status.HTTP_201_CREATED)


class FriendListView(APIView):
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        FriendTuple = namedtuple("Friend", ('friends', 'friendRequests'))

        friend = FriendTuple(friendRequests=request.user.friendRequests.all(), friends=request.user.friends.all())
        serializer = ProfileSerializer(friend)
        return Response(serializer.data, status=status.HTTP_200_OK)


class LikePost(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        id = request.data["id"]
        p = ProfilePost.objects.get(pk=id)
        p.likes = p.likes + 1
        p.save()
        return Response(status=status.HTTP_200_OK)


class JoinGroup(APIView):
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        group = Group.objects.get(pk=request.data["group"])
        user = request.user
        group.pendingGroupRequest.add(user)
        group.save()
        return Response(status=status.HTTP_200_OK)


def logged(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None and user.is_superuser:
            if user.is_active:
                login(request, user)
                return redirect("../admin-panel/")
        else:
            return redirect('/')
    else:
        return redirect('/')


def adminPanel(request):
    if request.user.is_authenticated:
        requests = []
        groups = Group.objects.all()
        posts = FormPost.objects.all()
        for group in groups:
            requests += group.pendingGroupRequest.all()
        return render(request, 'admin-panel.html', {'requests': requests, 'groups': groups, 'posts': posts})
    else:
        return redirect("/")


class AddGroupPost(APIView):
    queryset = GroupPost.objects.all()
    serializer_class = GroupPostSerializerAdmin

    parser_classes = (MultiPartParser,)

    def post(self, request, *args, **kwargs):
        serializer = GroupPostSerializerAdmin(data=request.data)
        print(request.data)
        if serializer.is_valid():
            serializer.save()
            return HttpResponse('post created')
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CreateGroup(APIView):
    queryset = Group.objects.all()
    serializer_class = GroupSerializerAdmin

    parser_classes = (MultiPartParser,)

    def post(self, request, *args, **kwargs):
        serializer = GroupSerializer(data=request.data)
        print(request.data)
        if serializer.is_valid():
            serializer.save()
            return HttpResponse('Group Created Successfully !')
        return HttpResponse(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class GroupUpdateView(UpdateAPIView):
    queryset = Group.objects.all()
    serializer_class = GroupSerializerAdmin


def acceptGroupRequest(request, userid, groupid):
    user = CustomUser.objects.get(id=userid)
    group = Group.objects.get(id=groupid)
    group.pendingGroupRequest.remove(user)
    group.user.add(user)
    requests = []
    groups = Group.objects.all()
    posts = FormPost.objects.all()
    for group in groups:
        requests += group.pendingGroupRequest.all()

1-03-2019_1.00am/bloodBank2/api/templates/admin-panel.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Janakalyan Blood Bank Admin</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static 'bubbly/vendor/bootstrap/css/bootstrap.min.css'%}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <!-- Google fonts - Popppins for copy-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,800">
    <!-- orion icons-->
    <link rel="stylesheet" href="{% static 'bubbly/css/orionicons.css'%}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'bubbly/css/style.default.css'%}" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'bubbly/css/custom.css'%}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'bubbly/img/favicon.png?3'%}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <!-- navbar-->
    <header class="header">
      <nav class="navbar navbar-expand-lg px-4 py-2 bg-white shadow"><a href="#" class="sidebar-toggler text-gray-500 mr-4 mr-lg-5 lead"><i class="fas fa-align-left"></i></a><a href="index.html" class="navbar-brand font-weight-bold text-uppercase text-base">Janakalyan Blood Bank Admin</a>
        <ul class="ml-auto d-flex align-items-center list-unstyled mb-0">
          <li class="nav-item">
            <form id="searchForm" class="ml-auto d-none d-lg-block">
              <div class="form-group position-relative mb-0">
                <button type="submit" style="top: -3px; left: 0;" class="position-absolute bg-white border-0 p-0"><i class="o-search-magnify-1 text-gray text-lg"></i></button>
                <input type="search" placeholder="Search ..." class="form-control form-control-sm border-0 no-shadow pl-4">
              </div>
            </form>
          </li>
          <li class="nav-item dropdown ml-auto"><a id="userInfo" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle"><img src="{% static 'bubbly/img/male.png'%}" alt="Jason Doe" style="max-width: 2.5rem;" class="img-fluid rounded-circle shadow"></a>
            <div aria-labelledby="userInfo" class="dropdown-menu"><a href="#" class="dropdown-item"><strong class="d-block text-uppercase headings-font-family">Admin</strong></a>
              
              <div class="dropdown-divider"></div><form action="../logout/" method="post">
                {%csrf_token%}
                <button style="background-color: rgba(0,0,0,0);width: 100%;padding: 0px;border: 0px;" type="submit"><a type="" class="sidebar-link text-muted" ><i class="o-exit-1 mr-3 text-gray"></i><span>Logout</span></a></button>
            </form>
            </div>
          </li>
        </ul>
      </nav>
    </header>
    <div class="d-flex align-items-stretch">
      <div id="sidebar" class="sidebar py-3">
        <div class="text-gray-400 text-uppercase px-3 px-lg-4 py-4 font-weight-bold small headings-font-family">MAIN</div>
        <ul class="sidebar-menu list-unstyled">
              <li class="sidebar-list-item"><a href="index.html" class="sidebar-link text-muted active"><i class="o-home-1 mr-3 text-gray"></i><span>Home</span></a></li>
              <form action="/group-add/" method="post">
                {%csrf_token%}
                <li class="sidebar-list-item"><button style="background-color: rgba(0,0,0,0);width: 100%;padding: 0px;border: 0px;" type="submit"><a type="" class="sidebar-link text-muted" ><i class="o-survey-1 mr-3 text-gray"></i><span>Add Group</span></a></button></li>
            </form>
              <form action="/admin-post/" method="post">
                {%csrf_token%}
                <li class="sidebar-list-item"><button style="background-color: rgba(0,0,0,0);width: 100%;padding: 0px;border: 0px;" type="submit"><a type="" class="sidebar-link text-muted" ><i class="o-survey-1 mr-3 text-gray"></i><span>New Group Post</span></a></button></li>
            </form>
            <form action="/create-form-post/" method="post">
                {%csrf_token%}
                <li class="sidebar-list-item"><button style="background-color: rgba(0,0,0,0);width: 100%;padding: 0px;border: 0px;" type="submit"><a type="" class="sidebar-link text-muted" ><i class="o-survey-1 mr-3 text-gray"></i><span>New Form Post</span></a></button></li>
            </form>
          <li class="sidebar-list-item"><a href="#" data-toggle="collapse" data-target="#pages" aria-expanded="false" aria-controls="pages" class="sidebar-link text-muted"><i class="o-wireframe-1 mr-3 text-gray"></i><span>Edit Group</span></a>
            <div id="pages" class="collapse">
              <ul class="sidebar-menu list-unstyled border-left border-primary border-thick">
                  {% for group in groups %}
                    <form action="/group-update/{{group.id}}/" method="put">
                        {%csrf_token%}
                        <li class="sidebar-list-item"><button style="background-color: rgba(0,0,0,0);width: 100%;padding: 0px;border: 0px;" type="submit"><a type="" class="sidebar-link text-muted pl-lg-5" >{{group.title}}</a></button></li>
                    </form>
                  {%endfor%}
                
              </ul>
            </div>
          </li>
            <form action="../logout/" method="post">
                {%csrf_token%}
                <li class="sidebar-list-item"><button style="background-color: rgba(0,0,0,0);width: 100%;padding: 0px;border: 0px;" type="submit"><a type="" class="sidebar-link text-muted" ><i class="o-exit-1 mr-3 text-gray"></i><span>Logout</span></a></button></li>
            </form>
              
        </ul>
       
      </div>
      <div class="page-holder w-100 d-flex flex-wrap">
        <div class="container-fluid px-xl-5">
            
            <section class="pt-5 ">
                <div class="row mb-3">
                    <h5>Form Responses</h5>
                </div>
            <div class="row">
              {% for post in posts %}
              <div class="col-lg-6 mb-4">
                <div class="card">
                  <div class="card-header">
                    <h6 class="text-uppercase mb-0">{{post.postDetails}}</h6>
                  </div>
                  <div class="card-body">
                    <table class="table table-striped table-hover card-text table-responsice">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Name</th>
                          <th>Phone</th>
                          <th>Response</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for response in post.formdata_set.all %}
                        <tr>
                          <th scope="row">{{forloop.counter}}</th>
                          <td>{{response.user.first_name}} {{response.user.last_name}}</td>
                          <td>{{response.user.phone}}</td>
                          <td>{{response.time}}</td>
                        </tr>
                        {%endfor%}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
                {%endfor%}
                
              
            </div>
          </section>    
            
          <section class="py-5">
              <div class="row mb-3">
                <h5>Requests</h5>
              </div>
            <div class="row">
                {% for group in groups %}
                    {% for request in group.pendingGroupRequest.all %}
              <div class="col-lg-12"><a href="#" class="message card px-5 py-3 mb-4 bg-hover-gradient-primary no-anchor-style">
                  <div class="row">
                    <div class="col-lg-3 d-flex align-items-center flex-column flex-lg-row text-center text-md-left"><img src="http://192.168.0.110:8000/media/{{request.profilePic}}" alt="..." style="max-width: 3rem" class="rounded-circle mx-3 my-2 my-lg-0">
                      <h6 class="mb-0">{{request.first_name}} {{request.last_name}}</h6>
                    </div>
                    <div class="col-lg-9 d-flex align-items-center flex-column flex-lg-row text-center text-md-left">
                      <div class="bg-gray-100 roundy px-4 py-1 mr-0 mr-lg-3 mt-2 mt-lg-0 text-dark exclode">{{group.title}}</div>
                        <p class="mb-0 mt-3 mt-lg-0 ">Group Join Request</p>
                        <form method="post" action="/group-accept/{{request.id}}/{{group.id}}/" class="mx-auto">{% csrf_token %}<button type="submit" class="mb-0 mt-3 mt-lg-0 mx-auto btn btn-secondary">Accept</button></form>
                    </div>
                  </div></a></div>
                {%endfor%}
                 {%endfor%}
            </div>
          </section>
          
        </div>
        <footer class="footer bg-white shadow align-self-end py-3 px-xl-5 w-100">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6 text-center text-md-left text-primary">
                <p class="mb-2 mb-md-0">Jankalyan Blood Bank &copy; 2018-2020</p>
              </div>
              <div class="col-md-6 text-center text-md-right text-gray-400">
                <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static 'bubbly/vendor/jquery/jquery.min.js'%}"></script>
    <script src="{% static 'bubbly/vendor/popper.js/umd/popper.min.js'%}"> </script>
    <script src="{% static 'bubbly/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'bubbly/vendor/jquery.cookie/jquery.cookie.js'%}"> </script>
    <script src="{% static 'bubbly/vendor/chart.js/Chart.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{% static 'bubbly/js/charts-home.js'%}"></script>
    <script src="{% static 'bubbly/js/front.js'%}"></script>
  </body>
</html>

1-03-2019_1.00am/bloodBank2/api/templates/admin-panel_old.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>admin post</title>
</head>
<body>

<h1 style="color:red">Responses</h1>
{% for post in posts %}
<h3 style="color:blue">{{post.postDetails}}</h3>
{% for response in post.formdata_set.all %}
    <h4>{{response.time}} - {{response.user}}</h4>
{% endfor %}
{% endfor %}


<h1 style="color:red">Add Group Post</h1>

<form action="/admin-post/" method="post">{% csrf_token %}
    <input type="submit" value="add group post">
</form>
<h1 style="color:red">update group details</h1>

{% for group in groups %}
<form action="/group-update/{{group.id}}/" method="put">{% csrf_token %}
    <input type="submit" value={{group.title}}>
</form>
{% endfor %}

<h1 style="color:red">Add Group</h1>


<form action="/group-add/" method="post">{% csrf_token %}
    <input type="submit" value="add group">
</form>

<h1 style="color:red">Accept Group Requests</h1>
{% for group in groups %}
<h3>{{group.title}}</h3>
{% for request in group.pendingGroupRequest.all %}
<form method="post" action="/group-accept/{{request.id}}/{{group.id}}/">{% csrf_token %}
    <input type="submit" value={{request.first_name}}>
</form>
{% endfor %}
{% endfor %}



<h1 style="color:red">accept post requests</h1>
<h1 style="color:red">remove user from group</h1>
{% for group in groups %}
<h3>{{group.title}}</h3>
{% for request in group.user.all %}
<form method="post" action="/group-reject/{{request.id}}/{{group.id}}/">{% csrf_token %}
    <input type="submit" value={{request.first_name}}>
</form>
{% endfor %}
{% endfor %}
<h1 style="color:red">Create Form Posts</h1>
<form action="/create-form-post/" method="post">{% csrf_token %}
<input type="submit" value="Create Post">
</form>
</body>
</html>

1-03-2019_1.00am/bloodBank2/api/templates/inside.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>inside</title>
</head>
<body>

</body>
</html>